package com.fanhua.jobtrack.common.enums;

import lombok.Getter;

/**
 * 全局错误码枚举
 */
@Getter
public enum ErrorCode {

    SUCCESS("SUCCESS", "操作成功"),
    VALIDATION_ERROR("VALIDATION_ERROR", "参数校验失败"),
    // 认证类错误（业务错误码稳定，前端按 code 判断，不依赖消息文本）
    AUTH_UNAUTHORIZED("AUTH_UNAUTHORIZED", "未认证或凭证缺失"),
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS", "账号或密码错误"),
    AUTH_TOKEN_INVALID("AUTH_TOKEN_INVALID", "Access Token 无效"),
    AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED", "Access Token 过期"),
    AUTH_REFRESH_INVALID("AUTH_REFRESH_INVALID", "Refresh Token 无效"),
    AUTH_REFRESH_EXPIRED("AUTH_REFRESH_EXPIRED", "Refresh Token 已过期"),
    AUTH_REFRESH_REUSED("AUTH_REFRESH_REUSED", "Refresh Token 已被轮换"),
    AUTH_SESSION_REVOKED("AUTH_SESSION_REVOKED", "会话已被注销"),
    AUTH_ACCOUNT_DISABLED("AUTH_ACCOUNT_DISABLED", "账号被禁用"),
    AUTH_LOGIN_LOCKED("AUTH_LOGIN_LOCKED", "登录暂时锁定，请稍后再试"),
    REGISTER_PASSWORD_MISMATCH("REGISTER_PASSWORD_MISMATCH", "两次输入的密码不一致"),
    USER_EMAIL_EXISTS("USER_EMAIL_EXISTS", "邮箱已存在"),
    USER_USERNAME_EXISTS("USER_USERNAME_EXISTS", "用户名已存在"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND", "资源不存在"),
    RESOURCE_FORBIDDEN("RESOURCE_FORBIDDEN", "无权访问资源"),
    COMPANY_NAME_EXISTS("COMPANY_NAME_EXISTS", "公司名称重复"),
    COMPANY_HAS_RELATIONS("COMPANY_HAS_RELATIONS", "公司存在关联记录"),
    POSITION_DUPLICATE("POSITION_DUPLICATE", "相同公司下岗位与来源组合已存在"),
    POSITION_HAS_APPLICATIONS("POSITION_HAS_APPLICATIONS", "岗位存在投递记录"),
    RESUME_FILE_TOO_LARGE("RESUME_FILE_TOO_LARGE", "简历文件过大"),
    RESUME_FILE_TYPE_UNSUPPORTED("RESUME_FILE_TYPE_UNSUPPORTED", "文件类型不支持"),
    RESUME_IN_USE("RESUME_IN_USE", "简历正在被投递记录使用"),
    RESUME_DUPLICATE("RESUME_DUPLICATE", "已存在相同内容的简历版本"),
    RESUME_FILE_MISSING("RESUME_FILE_MISSING", "简历文件已丢失"),
    APPLICATION_ALREADY_EXISTS("APPLICATION_ALREADY_EXISTS", "该岗位已有未结束投递记录"),
    APPLICATION_DUPLICATE("APPLICATION_DUPLICATE", "岗位已存在投递记录"),
    APPLICATION_POSITION_CLOSED("APPLICATION_POSITION_CLOSED", "岗位已关闭，不能创建投递"),
    APPLICATION_INVALID_STATUS_TRANSITION("APPLICATION_INVALID_STATUS_TRANSITION", "非法状态流转"),
    APPLICATION_IDEMPOTENCY_KEY_CONFLICT("IDEMPOTENCY_KEY_CONFLICT", "幂等键对应的请求参数不一致"),
    APPLICATION_IDEMPOTENCY_IN_PROGRESS("IDEMPOTENCY_IN_PROGRESS", "相同幂等请求正在处理中"),
    APPLICATION_VERSION_CONFLICT("APPLICATION_VERSION_CONFLICT", "投递记录版本已变化，请刷新后重试"),
    APPLICATION_DELETE_NOT_ALLOWED("APPLICATION_DELETE_NOT_ALLOWED", "只有未投递的草稿记录允许删除，请改用归档"),
    APPLICATION_RESUME_CHANGE_NOT_ALLOWED("APPLICATION_RESUME_CHANGE_NOT_ALLOWED", "当前状态不允许更换简历"),
    INTERVIEW_TIME_INVALID("INTERVIEW_TIME_INVALID", "面试时间不合法"),
    REMINDER_TIME_INVALID("REMINDER_TIME_INVALID", "提醒时间不合法"),
    OPTIMISTIC_LOCK_CONFLICT("OPTIMISTIC_LOCK_CONFLICT", "数据已被其他请求修改"),
    RATE_LIMITED("RATE_LIMITED", "请求过于频繁"),
    INTERNAL_ERROR("INTERNAL_ERROR", "系统内部错误");

    private final String code;
    private final String defaultMessage;

    ErrorCode(String code, String defaultMessage) {
        this.code = code;
        this.defaultMessage = defaultMessage;
    }
}
